
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
    - deployml_network
    ports:
    - 5672:5672
    - 5673:5673
    - 15672:15672

  db_server:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
    - 27017:27017
    networks:
    - deployml_network

  web_server:
    image: ml-jumpstart-kit/web_server
    build: ./web_server
    ports:
      - 8080:80
    networks:
      - deployml_network
    restart: on-failure
    depends_on:
      - rabbitmq
      - db_server
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db_server
      - QUEUE_NAME=ml_queue
    links:
      - rabbitmq

  model_server:
    image: ml-jumpstart-kit/model_server
    build: ./model_server
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db_server
      - QUEUE_NAME=ml_queue
      - HEART_BEAT_TIMEOUT=120
      - BLOCKED_CONNECTION_TIMEOUT=300
    networks:
      - deployml_network
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
    deployml_network:
